### ISSUE TITLE
Add  font-display option

### ISSUE THREAD

**Issue by nosovk** [SirPole/google-fonts-plugin#9]
Currently further font loading optimization available
 font-display: swap;
Info: https://css-tricks.com/almanac/properties/f/font-display/
could we add that param to options in the config?

**Comment by SirPole** [comment]
Hey! If you're using `encode: true`, you shouldn't need `font-display`, as it's usefulness lies when browser is waiting for font files to be downloaded after it has already parsed the font-face... Therefore I've added this feature only when `encode` is `false`. Released in [4.1.0](https://www.npmjs.com/package/google-fonts-plugin) 🚀

**Comment by SirPole** [comment]
Apparently, google fonts now supports font-display natively: https://www.zachleat.com/web/google-fonts-display/

I'll reimplement the feature to support this.

**Comment by duongthienlee** [comment]
> Apparently, google fonts now supports font-display natively: https://www.zachleat.com/web/google-fonts-display/
> 
> I'll reimplement the feature to support this.

So you mean, until you reimplement the feature, if I want to use `font-display`, I need to set `encode` to `false` ?
Anyways thank for your great plugin.

**Comment by SirPole** [comment]
Hey... Sorry for such a delayed answer. :( 

You don't need font-display when you're encoding the fonts to base64, because they're available in the instant the css file is loaded. There is no benefit in adding font-display property. When you disable encoding, then you do take benefit from font-display, because you wait until the fonts themselves are downloaded....

Hope that clarifies it :)
